/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.diplom2.data.GUI;

import com.mycompany.diplom2.data.DataService;
import com.mycompany.diplom2.data.GUI.extraWindows.newSetFrame;
import com.mycompany.diplom2.data.Sensors;
import com.mycompany.diplom2.data.SetOfSensors;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author 1
 */
public class ChooseSetOfSensors extends javax.swing.JFrame {

    /**
     * Creates new form ChooseSetOfSensors
     */
    public ChooseSetOfSensors() {
        initComponents();
        tableOfSets.setSelectionMode(NORMAL);
        setColumnsWidth(ContentOfTheSet);
        try {
            DataService<SetOfSensors> ds;
            ds = new DataService(SetOfSensors.class);
            SetOfSensors allSets[] = ds.getAllAsArray();
            ArrayList<Object[]> allItems = new ArrayList<Object[]>();
            int countOfSets = allSets.length; 
            if(countOfSets == 0){
                String[] columnNames = {"Имя набора"};
                String[] emptySet = {"Нет наборов сенсоров"};
                allItems.add(allSets);
                TableModel tm = new CustomTableModel<String>(allItems, columnNames);
                tableOfSets.setModel(tm);
                tableOfSets.setEnabled(false);
            }
            else{
            //тут заполняю таблицу наборами и леплю листенер
                String[] columnNames = {"Имя набора"};
                allItems.add(allSets);
                TableModel tm = new CustomTableModel<SetOfSensors>(allItems, columnNames);
                tableOfSets.setModel(tm);
                
                tableOfSets.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

                    public void valueChanged(ListSelectionEvent e) {
                        try {
                            String[] columnNames = {"Имя сенсора", "№"};
                            SetOfSensors el =(SetOfSensors) tableOfSets.getModel().getValueAt(tableOfSets.getSelectedRow(), 0);
                            ArrayList<Object[]> allItems = new ArrayList<Object[]>();
                            Sensors[] set = el.getSetAsArray();
                            allItems.add(set);
                            int countOfSensors = set.length;
                            String[] nums = new String[countOfSensors];
                            for(int i = 0; i<countOfSensors;i++)
                                nums[i] = Integer.toString(i+1);
                            allItems.add(nums);
                            TableModel tm = new CustomTableModel<Sensors>(allItems, columnNames);
                            ContentOfTheSet.setModel(tm);
                            setColumnsWidth(ContentOfTheSet);
                            changeSetButton.setEnabled(true);
                        } catch (SQLException ex) {
                            Logger.getLogger(ChooseSetOfSensors.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                });
            }

        } catch (SQLException ex) {
            Logger.getLogger(ChooseSetOfSensors.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        tableOfSets = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        ContentOfTheSet = new javax.swing.JTable();
        newSetButton = new javax.swing.JButton();
        changeSetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 300));
        setPreferredSize(new java.awt.Dimension(700, 400));
        setResizable(false);
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0};
        getContentPane().setLayout(layout);

        tableOfSets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Имя набора"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableOfSets);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 256;
        gridBagConstraints.ipady = 309;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE_LEADING;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 14, 0);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        ContentOfTheSet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Имя сенсора", "№"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ContentOfTheSet.setAutoscrolls(false);
        ContentOfTheSet.setEnabled(false);
        ContentOfTheSet.setFocusable(false);
        jScrollPane2.setViewportView(ContentOfTheSet);
        ContentOfTheSet.getColumnModel().getColumn(1).setResizable(false);
        ContentOfTheSet.getColumnModel().getColumn(1).setPreferredWidth(50);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 429;
        gridBagConstraints.ipady = 309;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE_TRAILING;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 14, 10);
        getContentPane().add(jScrollPane2, gridBagConstraints);

        newSetButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        newSetButton.setText("Создать новый набор");
        newSetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSetButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(newSetButton, gridBagConstraints);

        changeSetButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        changeSetButton.setText("Изменить выбранный набор");
        changeSetButton.setToolTipText("Сначала необходимо выбрать набор");
        changeSetButton.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        getContentPane().add(changeSetButton, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newSetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSetButtonActionPerformed
        try {
            // TODO add your handling code here:
            this.setVisible(false);
            newSetFrame.run();
        } catch (SQLException ex) {
            Logger.getLogger(ChooseSetOfSensors.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_newSetButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    public final static void setColumnsWidth(JTable table) {
    table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    JTableHeader th = table.getTableHeader();
    for (int i = 0; i < table.getColumnCount(); i++) {
        TableColumn column = table.getColumnModel().getColumn(i);
        int prefWidth = (i == 0? table.getWidth()-40 : 40);
        column.setPreferredWidth(prefWidth);
    }
   }
    
      public static void run(){
        ChooseSetOfSensors form = new ChooseSetOfSensors();
        form.setVisible(true);
        form.setLocationRelativeTo(null);
      }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ContentOfTheSet;
    private javax.swing.JButton changeSetButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton newSetButton;
    private javax.swing.JTable tableOfSets;
    // End of variables declaration//GEN-END:variables
}
