/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.diplom2.data.GUI;

import com.mycompany.diplom2.data.Sensors;
import com.mycompany.diplom2.data.SetOfSensors;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.StandardCategoryToolTipGenerator;
import org.jfree.chart.plot.SpiderWebPlot;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author 1
 */
public class DiagramFrame extends javax.swing.JFrame {

    /**
     * Creates new form DiagramFrame
     */
    JFreeChart chart;
    SetOfSensors set;
    Double[] resoltSignal;
    
    public DiagramFrame(SetOfSensors set, Double[] resoltSignal) {
        initComponents();
        this.set = set;
        this.resoltSignal = resoltSignal;
        chartBuild();
    }
    
    public void chartBuild(){
        try {
            CategoryDataset cd = new DefaultCategoryDataset();
            Sensors[] setItems = set.getSetAsArray();
            int itemsCount = setItems.length;
            
            for(int i = 0; i< itemsCount; i++)
                ((DefaultCategoryDataset)cd).addValue(resoltSignal[i], set.getNameOfSet(), setItems[i].getSensorShortName());
            
            //второй график для примера
            java.util.Random rand = new java.util.Random();
            for(int i = 0; i< itemsCount; i++)
                ((DefaultCategoryDataset)cd).addValue(rand.nextInt()%10, "random", setItems[i].getSensorShortName());
            
            SpiderWebPlot plot = new SpiderWebPlot(cd);
            chart = new JFreeChart("Визуальный отпечаток",Font.getFont("Arial"), plot, true);
            plot.setBackgroundPaint(Color.LIGHT_GRAY);
            plot.setSeriesOutlineStroke(new java.awt.BasicStroke(1.83f));
            plot.setToolTipGenerator(new org.jfree.chart.labels.StandardCategoryToolTipGenerator());

            ChartPanel chp = new ChartPanel(chart);
            panel.removeAll();
            panel.add(chp,BorderLayout.CENTER);
        } catch (SQLException ex) {
            Logger.getLogger(DiagramFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        savaAsPngButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setLayout(new javax.swing.BoxLayout(panel, javax.swing.BoxLayout.LINE_AXIS));

        savaAsPngButton.setText("Сохранить как png");
        savaAsPngButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savaAsPngButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 341, Short.MAX_VALUE)
                .addComponent(savaAsPngButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(savaAsPngButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savaAsPngButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savaAsPngButtonActionPerformed
        // TODO add your handling code here:
        try {
            // например в файл
            java.io.OutputStream stream = new java.io.FileOutputStream("chart.png");
            org.jfree.chart.ChartUtilities.writeChartAsPNG(stream, chart, 500, 500);
            javax.swing.JOptionPane.showMessageDialog(this, "chart.png сохранена!", "Сообщение", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch(java.io.IOException e) {
            System.err.println("Failed to render chart as png: "+ e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_savaAsPngButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void run(SetOfSensors set, Double[] resoltSignal) {
        final SetOfSensors fset = set;
        final Double[] fresoltSignal = resoltSignal;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiagramFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiagramFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiagramFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiagramFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DiagramFrame frame = new DiagramFrame(fset, fresoltSignal);
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panel;
    private javax.swing.JButton savaAsPngButton;
    // End of variables declaration//GEN-END:variables
}
